datagrid:
    product-grid:
        options:
            entityHint: product
            requireJSModules:
                - pim/datagrid/configure-columns-action
        source:
            acl_resource:      pim_enrich_product_index
            type:              pim_datasource_product
            entity:            '%pim_catalog.entity.product.class%'
            repository_method: createDatagridQueryBuilder
        columns:
            family:
                label:         Family
                data_name:     familyLabel
                selector:      product_family
            enabled:
                label:         Status
                type:          twig
                template:      PimDataGridBundle:Property:enabled.html.twig
                frontend_type: html
            created:
                label:         Created At
                type:          product_value_date
                frontend_type: date
            updated:
                label:         Updated At
                type:          product_value_date
                frontend_type: date
            groups:
                label:         Groups
                type:          product_groups
                selector:      product_groups
        properties:
            id: ~
            edit_link:
                type: url
                route: pim_enrich_product_edit
                params:
                    - id
                    - dataLocale
            delete_link:
                type: url
                route: pim_enrich_product_rest_remove
                params:
                    - id
            toggle_status_link:
                type: url
                route: pim_enrich_product_toggle_status
                params:
                    - id
        actions:
            edit:
                type:      navigate
                label:
                icon:
                link:      edit_link
                rowAction: true
            edit_attributes:
                type:      tab-redirect
                label:     Edit attributes of the product
                tab:       pim-product-edit-form-attributes
                icon:      pencil
                link:      edit_link
            edit_categories:
                type:  tab-redirect
                label: Classify the product
                tab:   pim-product-edit-form-categories
                icon:  folder-close
                link:  edit_link
            delete:
                type:  delete
                label: Delete the product
                icon:  trash
                link:  delete_link
                acl_resource: pim_enrich_product_remove
            toggle_status:
                type:  ajax
                label: Toggle status
                icon:  retweet
                link:  toggle_status_link
        mass_actions_groups:
            bulk_actions:
                label: pim_datagrid.mass_action_group.bulk_actions.label
            quick_export:
                label: pim_datagrid.mass_action_group.quick_export.label
        mass_actions:
            mass_edit:
                type: edit
                acl_resource: pim_enrich_mass_edit
                label: pim.grid.mass_action.mass_edit
                handler: product_mass_edit
                route: pim_enrich_mass_edit_product_action_choose
                launcherOptions:
                    group: bulk_actions
            sequential_edit:
                type: edit
                acl_resource: pim_enrich_product_edit_attributes
                label: pim.grid.mass_action.sequential_edit
                handler: sequential_edit
                route: pim_enrich_mass_edit_action_sequential_edit
                launcherOptions:
                    group: bulk_actions
            category_edit:
                type: edit
                acl_resource: pim_enrich_mass_edit
                label: pim.grid.mass_action.category_edit
                handler: product_mass_edit
                route: pim_enrich_mass_edit_product_action_choose
                route_parameters:
                    operationGroup: category-edit
                launcherOptions:
                    group: bulk_actions
            delete:
                type: delete
                label: pim.grid.mass_action.delete
                entity_name: product
                acl_resource: pim_enrich_product_remove
                handler: product_mass_delete
                messages:
                    confirm_title: pim_datagrid.mass_action.delete.confirm_title
                    confirm_content: pim_datagrid.mass_action.delete.confirm_content
                    confirm_ok: pim_datagrid.mass_action.delete.confirm_ok
                    success: pim_datagrid.mass_action.delete.success
                    error: pim_datagrid.mass_action.delete.error
                    empty_selection: pim_datagrid.mass_action.delete.empty_selection
                launcherOptions:
                    group: bulk_actions
            quick_export_grid_context_xlsx:
                type: export
                label: pim.grid.mass_action.quick_export.xlsx_grid_context
                handler: product_quick_export
                route: pim_datagrid_export_product_index
                route_parameters:
                    _format: xlsx
                    _contentType: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
                    _jobCode: xlsx_product_grid_context_quick_export
                    _displayedColumnsOnly: 1
                context:
                    withHeader: true
                messages:
                    empty_selection: pim_datagrid.mass_action.delete.empty_selection
                launcherOptions:
                    group: quick_export
            quick_export_xlsx:
                type: export
                label: pim.grid.mass_action.quick_export.xlsx_all
                handler: product_quick_export
                route: pim_datagrid_export_product_index
                route_parameters:
                    _format: xlsx
                    _contentType: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
                    _jobCode: xlsx_product_quick_export
                    _displayedColumnsOnly: 0
                context:
                    withHeader: true
                messages:
                    empty_selection: pim_datagrid.mass_action.delete.empty_selection
                launcherOptions:
                    group: quick_export
            quick_export_grid_context_csv:
                type: export
                label: pim.grid.mass_action.quick_export.csv_grid_context
                handler: product_quick_export
                route: pim_datagrid_export_product_index
                route_parameters:
                    _format: csv
                    _contentType: text/csv
                    _jobCode: csv_product_grid_context_quick_export
                    _displayedColumnsOnly: 1
                context:
                    withHeader: true
                messages:
                    empty_selection: pim_datagrid.mass_action.delete.empty_selection
                launcherOptions:
                    group: quick_export
            quick_export_csv:
                type: export
                label: pim.grid.mass_action.quick_export.csv_all
                handler: product_quick_export
                route: pim_datagrid_export_product_index
                route_parameters:
                    _format: csv
                    _contentType: text/csv
                    _jobCode: csv_product_quick_export
                    _displayedColumnsOnly: 0
                context:
                    withHeader: true
                messages:
                    empty_selection: pim_datagrid.mass_action.delete.empty_selection
                launcherOptions:
                    group: quick_export
        sorters: []
        filters: []
