Pim\Component\Catalog\Model\Product:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [identifier]
            message: The same identifier is already set on another product
        - Pim\Component\Catalog\Validator\Constraints\HasVariantAxes:
            groups:
                - Default
                - pim_catalog_variant_group
        - Pim\Component\Catalog\Validator\Constraints\UniqueVariantAxis:
            groups:
                - Default
                - pim_catalog_variant_group
        - Pim\Component\Catalog\Validator\Constraints\UniqueVariantGroup:
            groups:
                - Default
                - pim_catalog_variant_group
    properties:
        identifier:
            # TODO: TIP-722 - Add not Blank and Length validation here once the product value
            # identifier is removed.
            - Regex:
                pattern: '/^[^,;]+$/'
                message: 'regex.comma_or_semicolon.message'
    getters:
        values:
            - Symfony\Component\Validator\Constraints\Valid:
                traverse: true
