parameters:
    pim_catalog.completeness.checker.chained.class: Pim\Component\Catalog\Completeness\Checker\ChainedProductValueCompleteChecker
    pim_catalog.completeness.checker.media.class:   Pim\Component\Catalog\Completeness\Checker\MediaCompleteChecker
    pim_catalog.completeness.checker.metric.class:  Pim\Component\Catalog\Completeness\Checker\MetricCompleteChecker
    pim_catalog.completeness.checker.price.class:   Pim\Component\Catalog\Completeness\Checker\PriceCompleteChecker
    pim_catalog.completeness.checker.simple.class:  Pim\Component\Catalog\Completeness\Checker\SimpleCompleteChecker

services:
    pim_catalog.completeness.checker.chained:
        class: '%pim_catalog.completeness.checker.chained.class%'

    pim_catalog.completeness.checker.media:
        class: '%pim_catalog.completeness.checker.media.class%'
        tags:
            - { name: pim_catalog.completeness.checker.product_value, priority: 100 }

    pim_catalog.completeness.checker.metric:
        class: '%pim_catalog.completeness.checker.metric.class%'
        tags:
            - { name: pim_catalog.completeness.checker.product_value, priority: 100 }

    pim_catalog.completeness.checker.price:
        class: '%pim_catalog.completeness.checker.price.class%'
        tags:
            - { name: pim_catalog.completeness.checker.product_value, priority: 100 }

    pim_catalog.completeness.checker.simple:
        class: '%pim_catalog.completeness.checker.simple.class%'
        tags:
            - { name: pim_catalog.completeness.checker.product_value, priority: 150 }
