parameters:
    pim_catalog.query.product_query_builder_factory.class:        Pim\Component\Catalog\Query\ProductQueryBuilderFactory
    pim_catalog.query.product_query_builder.class:                Pim\Component\Catalog\Query\ProductQueryBuilder
    pim_catalog.query.filter.registry.class:                      Pim\Component\Catalog\Query\Filter\FilterRegistry
    pim_catalog.query.sorter.registry.class:                      Pim\Component\Catalog\Query\Sorter\SorterRegistry
    pim_catalog.query.filter.field_dumper.class:                  Pim\Bundle\CatalogBundle\Command\ProductQueryHelp\FieldFilterDumper
    pim_catalog.query.filter.attribute_dumper.class:              Pim\Bundle\CatalogBundle\Command\ProductQueryHelp\AttributeFilterDumper
    pim_catalog.doctrine.query.filter.object_id_resolver.class:   Pim\Bundle\CatalogBundle\Doctrine\Common\Filter\ObjectIdResolver
    pim_catalog.doctrine.query.filter.object_code_resolver.class: Pim\Bundle\CatalogBundle\Doctrine\Common\Filter\ObjectCodeResolver
    pim_catalog.query.elasticsearch.filter.identifier.class:      Pim\Bundle\CatalogBundle\Elasticsearch\Filter\IdentifierFilter
    pim_catalog.query.elasticsearch.filter.family.class:          Pim\Bundle\CatalogBundle\Elasticsearch\Filter\Field\FamilyFilter
    pim_catalog.query.elasticsearch.filter.category.class:        Pim\Bundle\CatalogBundle\Elasticsearch\Filter\Field\CategoryFilter
    pim_catalog.query.elasticsearch.filter.group.class:           Pim\Bundle\CatalogBundle\Elasticsearch\Filter\Field\GroupFilter
    pim_catalog.query.elasticsearch.filter.status.class:          Pim\Bundle\CatalogBundle\Elasticsearch\Filter\Field\StatusFilter
    pim_catalog.query.elasticsearch.filter.datetime.class:        Pim\Bundle\CatalogBundle\Elasticsearch\Filter\Field\DateTimeFilter
    pim_catalog.query.elasticsearch.filter.completeness.class: Pim\Bundle\CatalogBundle\Elasticsearch\Filter\Field\CompletenessFilter
    pim_catalog.query.elasticsearch.filter.date.class:            Pim\Bundle\CatalogBundle\Elasticsearch\Filter\Attribute\DateFilter
    pim_catalog.query.elasticsearch.filter.number.class:          Pim\Bundle\CatalogBundle\Elasticsearch\Filter\Attribute\NumberFilter
    pim_catalog.query.elasticsearch.filter.text.class: Pim\Bundle\CatalogBundle\Elasticsearch\Filter\Attribute\TextFilter
    pim_catalog.query.elasticsearch.filter.text_area.class: Pim\Bundle\CatalogBundle\Elasticsearch\Filter\Attribute\TextAreaFilter
    pim_catalog.query.elasticsearch.filter.option.class:          Pim\Bundle\CatalogBundle\Elasticsearch\Filter\Attribute\OptionFilter
    pim_catalog.query.elasticsearch.filter.options.class:         Pim\Bundle\CatalogBundle\Elasticsearch\Filter\Attribute\OptionsFilter
    pim_catalog.query.elasticsearch.filter.price.class: Pim\Bundle\CatalogBundle\Elasticsearch\Filter\Attribute\PriceFilter
    pim_catalog.query.elasticsearch.filter.metric.class: Pim\Bundle\CatalogBundle\Elasticsearch\Filter\Attribute\MetricFilter
    pim_catalog.query.elasticsearch.sorter.base.class:            Pim\Bundle\CatalogBundle\Elasticsearch\Sorter\BaseSorter

services:
    pim_catalog.query.product_query_builder_factory:
        class: '%pim_catalog.query.product_query_builder_factory.class%'
        arguments:
            - '%pim_catalog.query.product_query_builder.class%'
            - '@pim_catalog.repository.attribute'
            - '@pim_catalog.query.filter.registry'
            - '@pim_catalog.query.sorter.registry'
            - '@pim_catalog.factory.product_cursor'

    pim_catalog.query.filter.registry:
        class: '%pim_catalog.query.filter.registry.class%'
        arguments:
            - '@pim_catalog.repository.attribute'

    pim_catalog.query.sorter.registry:
        class: '%pim_catalog.query.sorter.registry.class%'

    pim_catalog.query.filter.field_dumper:
        class: '%pim_catalog.query.filter.field_dumper.class%'
        arguments:
            - '@pim_catalog.query.filter.registry'

    pim_catalog.query.filter.attribute_dumper:
        class: '%pim_catalog.query.filter.attribute_dumper.class%'
        arguments:
            - '@pim_catalog.query.filter.registry'
            - '@pim_catalog.repository.attribute'

    # PQB common utils
    pim_catalog.doctrine.query.filter.object_id_resolver:
        class: '%pim_catalog.doctrine.query.filter.object_id_resolver.class%'
        arguments:
            - '@akeneo_storage_utils.doctrine.smart_manager_registry'
        calls:
            - [ addFieldMapping, ['family', '%pim_catalog.entity.family.class%']]
            - [ addFieldMapping, ['option', '%pim_catalog.entity.attribute_option.class%']]
            - [ addFieldMapping, ['category', '%pim_catalog.entity.category.class%']]
            - [ addFieldMapping, ['group', '%pim_catalog.entity.group.class%']]

    pim_catalog.doctrine.query.filter.object_code_resolver:
        class: '%pim_catalog.doctrine.query.filter.object_code_resolver.class%'
        arguments:
            - '@akeneo_storage_utils.doctrine.smart_manager_registry'
        calls:
            - [ addFieldMapping, ['family', '%pim_catalog.entity.family.class%']]
            - [ addFieldMapping, ['option', '%pim_catalog.entity.attribute_option.class%']]
            - [ addFieldMapping, ['category', '%pim_catalog.entity.category.class%']]
            - [ addFieldMapping, ['group', '%pim_catalog.entity.group.class%']]

    # Fields filters
    pim_catalog.query.elasticsearch.filter.identifier:
        class: '%pim_catalog.query.elasticsearch.filter.identifier.class%'
        arguments:
            - ['identifier']
            - ['pim_catalog_identifier']
            - ['STARTS WITH', 'CONTAINS', 'DOES NOT CONTAIN', '=', '!=', 'IN', 'NOT IN']
        tags:
            - { name: 'pim_catalog.elasticsearch.query.filter', priority: 30 }

    pim_catalog.query.elasticsearch.filter.family:
        class: '%pim_catalog.query.elasticsearch.filter.family.class%'
        arguments:
            - ['family']
            - ['IN', 'NOT IN', 'EMPTY', 'NOT EMPTY']
        tags:
            - { name: 'pim_catalog.elasticsearch.query.filter', priority: 30 }

    pim_catalog.query.elasticsearch.filter.group:
        class: '%pim_catalog.query.elasticsearch.filter.group.class%'
        arguments:
            - ['groups']
            - ['IN', 'NOT IN', 'EMPTY', 'NOT EMPTY']
        tags:
            - { name: 'pim_catalog.elasticsearch.query.filter', priority: 30 }

    pim_catalog.query.elasticsearch.filter.category:
        class: '%pim_catalog.query.elasticsearch.filter.category.class%'
        arguments:
            - '@pim_catalog.repository.category'
            - ['categories']
            - ['IN', 'NOT IN', 'UNCLASSIFIED', 'IN OR UNCLASSIFIED', 'IN CHILDREN', 'NOT IN CHILDREN']
        tags:
            - { name: 'pim_catalog.elasticsearch.query.filter', priority: 30 }

    pim_catalog.query.elasticsearch.filter.status:
        class: '%pim_catalog.query.elasticsearch.filter.status.class%'
        arguments:
            - ['enabled']
            - ['=', '!=']
        tags:
            - { name: 'pim_catalog.elasticsearch.query.filter', priority: 30 }

    pim_catalog.doctrine.elasticsearch.filter.datetime:
        class: '%pim_catalog.query.elasticsearch.filter.datetime.class%'
        arguments:
            - '@akeneo_batch.job.job_instance_repository'
            - '@akeneo_batch.job_repository'
            - ['created', 'updated']
            -
                - '='
                - '<'
                - '>'
                - 'BETWEEN'
                - 'NOT BETWEEN'
                - 'EMPTY'
                - 'NOT EMPTY'
                - '!='
                - 'SINCE LAST N DAYS'
                - 'SINCE LAST JOB'
        tags:
            - { name: 'pim_catalog.elasticsearch.query.filter', priority: 30 }

    pim_catalog.query.elasticsearch.filter.completeness:
        class: '%pim_catalog.query.elasticsearch.filter.completeness.class%'
        arguments:
            - '@pim_catalog.repository.cached_channel'
            - ['completeness']
            -
                - 'NOT EQUALS ON AT LEAST ONE LOCALE'
                - 'EQUALS ON AT LEAST ONE LOCALE'
                - 'GREATER THAN ON AT LEAST ONE LOCALE'
                - 'GREATER OR EQUALS THAN ON AT LEAST ONE LOCALE'
                - 'LOWER OR EQUALS THAN ON AT LEAST ONE LOCALE'
                - 'LOWER THAN ON AT LEAST ONE LOCALE'
                - 'GREATER THAN ON ALL LOCALES'
                - 'GREATER OR EQUALS THAN ON ALL LOCALES'
                - 'LOWER OR EQUALS THAN ON ALL LOCALES'
                - 'LOWER THAN ON ALL LOCALES'
                - '!='
                - '='
                - '>'
                - '>='
                - '<='
                - '<'
        tags:
            - { name: 'pim_catalog.elasticsearch.query.filter', priority: 30 }

    # Attributes filters
    pim_catalog.query.elasticsearch.filter.number:
        class: '%pim_catalog.query.elasticsearch.filter.number.class%'
        arguments:
            - '@pim_catalog.validator.helper.attribute'
            - ['pim_catalog_number']
            - ['<', '<=', '=', '!=', '>=', '>', 'EMPTY', 'NOT EMPTY']
        tags:
            - { name: 'pim_catalog.elasticsearch.query.filter', priority: 30 }

    pim_catalog.query.elasticsearch.filter.options:
        class: '%pim_catalog.query.elasticsearch.filter.options.class%'
        arguments:
            - '@pim_catalog.validator.helper.attribute'
            - '@pim_catalog.repository.attribute_option'
            - ['pim_catalog_multiselect']
            - ['IN', 'NOT IN', 'EMPTY', 'NOT EMPTY']
        tags:
            - { name: 'pim_catalog.elasticsearch.query.filter', priority: 30 }

    pim_catalog.doctrine.query.filter.date:
        class: '%pim_catalog.query.elasticsearch.filter.date.class%'
        arguments:
            - '@pim_catalog.validator.helper.attribute'
            - ['pim_catalog_date']
            - ['=', '<', '>', 'BETWEEN', 'NOT BETWEEN', 'EMPTY', 'NOT EMPTY', '!=']
        tags:
            - { name: 'pim_catalog.elasticsearch.query.filter', priority: 30 }

    pim_catalog.query.elasticsearch.filter.text:
        class: '%pim_catalog.query.elasticsearch.filter.text.class%'
        arguments:
            - '@pim_catalog.validator.helper.attribute'
            - ['pim_catalog_text']
            - ['STARTS WITH', 'ENDS WITH', 'CONTAINS', 'DOES NOT CONTAIN', '=', 'EMPTY', 'NOT EMPTY', '!=']
        tags:
            - { name: 'pim_catalog.elasticsearch.query.filter', priority: 30 }

    pim_catalog.query.elasticsearch.filter.text_area:
        class: '%pim_catalog.query.elasticsearch.filter.text_area.class%'
        arguments:
            - '@pim_catalog.validator.helper.attribute'
            - ['pim_catalog_textarea']
            - ['STARTS WITH', 'ENDS WITH', 'CONTAINS', 'DOES NOT CONTAIN', '=', 'EMPTY', 'NOT EMPTY', '!=']
        tags:
            - { name: 'pim_catalog.elasticsearch.query.filter', priority: 30 }

    pim_catalog.query.elasticsearch.filter.option:
        class: '%pim_catalog.query.elasticsearch.filter.option.class%'
        arguments:
            - '@pim_catalog.validator.helper.attribute'
            - '@pim_catalog.repository.attribute_option'
            - ['pim_catalog_simpleselect']
            - ['IN', 'EMPTY', 'NOT EMPTY', 'NOT IN']
        tags:
            - { name: 'pim_catalog.elasticsearch.query.filter', priority: 30 }

    pim_catalog.query.elasticsearch.filter.price:
        class: '%pim_catalog.query.elasticsearch.filter.price.class%'
        arguments:
            - '@pim_catalog.validator.helper.attribute'
            - '@pim_catalog.repository.currency'
            - ['pim_catalog_price_collection']
            - ['<', '<=', '=', '!=', '>=', '>', 'EMPTY', 'EMPTY FOR CURRENCY', 'EMPTY ON ALL CURRENCIES', 'NOT EMPTY', 'NOT EMPTY ON AT LEAST ONE CURRENCY', 'NOT EMPTY FOR CURRENCY']
        tags:
            - { name: 'pim_catalog.elasticsearch.query.filter', priority: 30 }

    pim_catalog.query.elasticsearch.filter.metric:
        class: '%pim_catalog.query.elasticsearch.filter.metric.class%'
        arguments:
            - '@pim_catalog.validator.helper.attribute'
            - '@akeneo_measure.manager'
            - '@akeneo_measure.measure_converter'
            - ['pim_catalog_metric']
            - ['<', '<=', '=', '!=', '>=', '>', 'EMPTY', 'EMPTY FOR CURRENCY', 'EMPTY ON ALL CURRENCIES', 'NOT EMPTY', 'NOT EMPTY ON AT LEAST ONE CURRENCY', 'NOT EMPTY FOR CURRENCY']
        tags:
            - { name: 'pim_catalog.elasticsearch.query.filter', priority: 30 }

    # Fields sorters
    pim_catalog.query.elasticsearch.sorter.base:
        class: '%pim_catalog.query.elasticsearch.sorter.base.class%'
        arguments:
            - ['updated', 'created']
        tags:
            - { name: 'pim_catalog.elasticsearch.query.sorter', priority: 30 }
