parameters:
    pim_catalog.normalizer.indexing.product.class: Pim\Component\Catalog\Normalizer\Indexing\ProductNormalizer
    pim_catalog.normalizer.indexing.product.properties.class: Pim\Component\Catalog\Normalizer\Indexing\Product\PropertiesNormalizer
    pim_catalog.normalizer.indexing.product.associations.class: Pim\Component\Catalog\Normalizer\Indexing\Product\AssociationsNormalizer
    pim_catalog.normalizer.indexing.product.product_values.class: Pim\Component\Catalog\Normalizer\Indexing\Product\ProductValuesNormalizer
    pim_catalog.normalizer.indexing.product.product_value.class: Pim\Component\Catalog\Normalizer\Indexing\Product\ProductValueNormalizer
    pim_catalog.normalizer.indexing.product.price.class: Pim\Component\Catalog\Normalizer\Indexing\Product\PriceNormalizer
    pim_catalog.normalizer.indexing.product.metric.class: Pim\Component\Catalog\Normalizer\Indexing\Product\MetricNormalizer
    pim_catalog.normalizer.indexing.datetime.class: Pim\Component\Catalog\Normalizer\Indexing\DateTimeNormalizer
    pim_catalog.normalizer.indexing.file.class: Pim\Component\Catalog\Normalizer\Indexing\FileNormalizer
    pim_catalog.normalizer.indexing.attribute_option.class: Pim\Component\Catalog\Normalizer\Indexing\AttributeOptionNormalizer
services:
    pim_catalog.normalizer.indexing.product:
        class: '%pim_catalog.normalizer.indexing.product.class%'
        arguments:
            - '@pim_catalog.normalizer.indexing.product.properties'
            - '@pim_catalog.normalizer.indexing.product.associations'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pim_catalog.normalizer.indexing.product.properties:
        class: '%pim_catalog.normalizer.indexing.product.properties.class%'
        arguments:
            - '@pim_catalog.normalizer.standard.product.properties'
        tags:
            - { name: pim_serializer.normalizer, priority: 40 }

    pim_catalog.normalizer.indexing.product.associations:
        class: '%pim_catalog.normalizer.indexing.product.associations.class%'
        arguments:
            - '@pim_catalog.normalizer.standard.product.associations'
        tags:
            - { name: pim_serializer.normalizer, priority: 40 }

    pim_catalog.normalizer.indexing.product.product_values:
        class: '%pim_catalog.normalizer.indexing.product.product_values.class%'
        arguments:
            - '@pim_catalog.normalizer.standard.product.product_values'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pim_catalog.normalizer.indexing.product.product_value:
        class: '%pim_catalog.normalizer.indexing.product.product_value.class%'
        arguments:
            - '@pim_catalog.normalizer.standard.product.product_value'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pim_catalog.normalizer.indexing.product.price:
        class: '%pim_catalog.normalizer.indexing.product.price.class%'
        arguments:
            - '@pim_catalog.normalizer.standard.product.price'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pim_catalog.normalizer.indexing.product.metric:
        class: '%pim_catalog.normalizer.indexing.product.metric.class%'
        arguments:
            - '@pim_catalog.normalizer.standard.product.metric'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pim_catalog.normalizer.indexing.datetime:
        class: '%pim_catalog.normalizer.indexing.datetime.class%'
        arguments:
            - '@pim_catalog.normalizer.standard.datetime'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pim_catalog.normalizer.indexing.file:
        class: '%pim_catalog.normalizer.indexing.file.class%'
        arguments:
            - '@pim_catalog.normalizer.standard.file'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pim_catalog.normalizer.indexing.attribute_option:
        class: '%pim_catalog.normalizer.indexing.attribute_option.class%'
        arguments:
            - '@pim_catalog.normalizer.standard.attribute_option'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }
