services:
    akeneo_elastic_search.index_configuration.loader:
        class: 'Akeneo\Bundle\ElasticSearchBundle\IndexConfiguration\Loader'
        arguments:
            - '%akeneo_elastic_search.index_configuration.files%'

    akeneo_elastic_search.client_builder:
        class: 'Elasticsearch\ClientBuilder'

    akeneo_elastic_search.client:
        class: 'Akeneo\Bundle\ElasticSearchBundle\Client'
        arguments:
            - '@akeneo_elastic_search.client_builder'
            - '%akeneo_elastic_search.hosts%'
            - '%akeneo_elastic_search.index_name%'
