services:
    acme_range.updater.setter.range_value:
        class: '%pim_catalog.updater.setter.value.class%'
        parent: pim_catalog.updater.setter.abstract
        arguments:
            - ['acme_type_range']
        tags:
            - { name: 'pim_catalog.updater.setter' }
