parameters:
    pim_reference_data.normalizer.indexing.product.reference_data.class: Pim\Component\ReferenceData\Normalizer\Indexing\Product\ReferenceDataNormalizer

services:
    pim_reference_data.normalizer.indexing.product.reference_data:
        class: '%pim_reference_data.normalizer.indexing.product.reference_data.class%'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }
