parameters:
    pim_datagrid.extension.selector.orm.product.label_selector.class:         Pim\Bundle\DataGridBundle\Extension\Selector\Orm\Product\LabelSelector
    pim_datagrid.extension.selector.orm.product.groups_selector.class:        Pim\Bundle\DataGridBundle\Extension\Selector\Orm\Product\GroupsSelector
    pim_datagrid.extension.selector.orm.product.completeness_selector.class:  Pim\Bundle\DataGridBundle\Extension\Selector\Orm\Product\CompletenessSelector
    pim_datagrid.extension.selector.orm.product.family_selector.class:        Pim\Bundle\DataGridBundle\Extension\Selector\Orm\Product\FamilySelector
    pim_datagrid.extension.selector.orm.product.in_group_selector.class:      Pim\Bundle\DataGridBundle\Extension\Selector\Orm\Product\InGroupSelector
