parameters:
    pim_datagrid.extension.sorter.orm.field_sorter.class:            Pim\Bundle\DataGridBundle\Extension\Sorter\Orm\FieldSorter
    pim_datagrid.extension.sorter.product.field_sorter.class:        Pim\Bundle\DataGridBundle\Extension\Sorter\Product\FieldSorter
    pim_datagrid.extension.sorter.product.value_sorter.class:        Pim\Bundle\DataGridBundle\Extension\Sorter\Product\ValueSorter
    pim_datagrid.extension.sorter.product.completeness_sorter.class: Pim\Bundle\DataGridBundle\Extension\Sorter\Product\CompletenessSorter
    pim_datagrid.extension.sorter.product.family_sorter.class:       Pim\Bundle\DataGridBundle\Extension\Sorter\Product\FamilySorter
    pim_datagrid.extension.sorter.product.in_group_sorter.class:     Pim\Bundle\DataGridBundle\Extension\Sorter\Product\InGroupSorter
    pim_datagrid.extension.sorter.product.is_associated_sorter.class: Pim\Bundle\DataGridBundle\Extension\Sorter\Product\IsAssociatedSorter
