parameters:
    pim_user.context.user.class: Pim\Bundle\UserBundle\Context\UserContext

services:
    pim_user.context.user:
        class: '%pim_user.context.user.class%'
        arguments:
            - '@security.token_storage'
            - '@pim_catalog.repository.locale'
            - '@pim_catalog.repository.channel'
            - '@pim_enrich.repository.category_tree'
            - '@request_stack'
            - '@pim_catalog.builder.choices'
            - '%locale%'
