services:
    pim_analytics.data_collector.storage:
        class: '%pim_analytics.data_collector.storage.class%'
        arguments:
            - '%database_host%'
            - '%database_name%'
            - '%database_user%'
            - '%database_password%'
        tags:
            - { name: pim_analytics.data_collector, type: system_info_report }
            - { name: pim_analytics.data_collector, type: system_info_report }
