Pim\Component\Catalog\Model\ProductModel:
    type: entity
    table: pim_catalog_product_model
    changeTrackingPolicy: DEFERRED_EXPLICIT
    gedmo:
        tree:
            type: nested
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        identifier:
            type: string
            length: 255
            unique: true
            nullable: false
        rawValues:
            type: native_json
            column: raw_values
        root:
            type: integer
            gedmo:
                - treeRoot
        level:
            type: integer
            column: lvl
            gedmo:
                - treeLevel
        left:
            type: integer
            column: lft
            gedmo:
                - treeLeft
        right:
            type: integer
            column: rgt
            gedmo:
                - treeRight
    oneToMany:
        childrenModels:
            targetEntity: Pim\Component\Catalog\Model\ProductModelInterface
            mappedBy: parentModel
            cascade:
                - persist
            orderBy:
                left: ASC
    manyToOne:
        family:
            targetEntity: Pim\Component\Catalog\Model\FamilyInterface
            joinColumns:
                family_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
        parentModel:
            targetEntity: Pim\Component\Catalog\Model\ProductModelInterface
            joinColumns:
                model_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
            gedmo:
                - treeParent
    manyToMany:
        categories:
            targetEntity: Pim\Component\Catalog\Model\CategoryInterface
            joinTable:
                name: pim_catalog_category_product_model
                joinColumns:
                    product_id:
                        referencedColumnName: id
                        onDelete: CASCADE
                inverseJoinColumns:
                    category_id:
                        referencedColumnName: id
                        onDelete: CASCADE