extensions:
    pim-export-history-index:
        module: pim/form/common/index/index
        config:
            title: pim_enrich.index.export_history.title

    pim-export-history-index-grid:
        module: pim/form/common/index/grid
        parent: pim-export-history-index
        position: 1000
        targetZone: content
        config:
            alias: export-execution-grid
            metadata:
                jobType: export
