parameters:
    pim_catalog.event_subscriber.orm.inject_product_reference.class: Pim\Bundle\CatalogBundle\EventSubscriber\ORM\InjectProductReferenceSubscriber

services:
    pim_catalog.event_subscriber.orm.inject_product_reference:
        class: '%pim_catalog.event_subscriber.orm.inject_product_reference.class%'
        arguments:
            - '%pim_catalog.entity.product.class%'
        tags:
            - { name: doctrine.event_subscriber }
